-- MySQL Script generated by MySQL Workbench
-- Tue Dec  4 23:06:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CadastroCidadao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CadastroCidadao` ;

-- -----------------------------------------------------
-- Schema CadastroCidadao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CadastroCidadao` DEFAULT CHARACTER SET utf8 ;
USE `CadastroCidadao` ;

-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Cidadao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Cidadao` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Cidadao` (
  `cpfCidadao` CHAR(11) NOT NULL,
  `nomeCidadao` VARCHAR(50) NOT NULL,
  `nomeSocial` VARCHAR(45) NULL,
  `nomeMae` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `sexoNascimento` CHAR(10) NOT NULL,
  `generoDeclarado` VARCHAR(20) NULL,
  `codigoUF` CHAR(2) NOT NULL,
  `codigoRacaCor` INT(1) NOT NULL,
  `codigoEstadoCivil` INT(1) NOT NULL,
  `codigoEscolaridade` INT(1) NOT NULL,
  `codigoOcupacao` INT(1) NOT NULL,
  `codigoVinculo` INT(1) NOT NULL,
  `rendaIndividual` FLOAT NOT NULL,
  `rendaFamiliar` FLOAT NOT NULL,
  `tipoBeneficio` VARCHAR(50) NULL,
  `valorBeneficio` FLOAT NULL,
  `cartaoSUS` CHAR(15) NULL,
  PRIMARY KEY (`cpfCidadao`),
  CONSTRAINT `codigoRacaCor`
    FOREIGN KEY (`codigoRacaCor`)
    REFERENCES `CadastroCidadao`.`Raca_Cor` (`codigoRacaCor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoEstadoCivil`
    FOREIGN KEY (`codigoEstadoCivil`)
    REFERENCES `CadastroCidadao`.`Estado_Civil` (`codigoEstadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoEscolaridade`
    FOREIGN KEY (`codigoEscolaridade`)
    REFERENCES `CadastroCidadao`.`Escolaridade` (`codigoEscolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoOcupacao`
    FOREIGN KEY (`codigoOcupacao`)
    REFERENCES `CadastroCidadao`.`Ocupacao` (`codigoOcupacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoVinculo`
    FOREIGN KEY (`codigoVinculo`)
    REFERENCES `CadastroCidadao`.`Vinculo` (`codigoVinculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoUF`
    FOREIGN KEY (`codigoUF`)
    REFERENCES `CadastroCidadao`.`UF` (`codigoUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `codigoRacaCor_idx` ON `CadastroCidadao`.`Cidadao` (`codigoRacaCor` ASC) VISIBLE;

CREATE INDEX `codigoEstadoCivil_idx` ON `CadastroCidadao`.`Cidadao` (`codigoEstadoCivil` ASC) VISIBLE;

CREATE INDEX `codigoEscolaridade_idx` ON `CadastroCidadao`.`Cidadao` (`codigoEscolaridade` ASC) VISIBLE;

CREATE INDEX `codigoOcupacao_idx` ON `CadastroCidadao`.`Cidadao` (`codigoOcupacao` ASC) VISIBLE;

CREATE INDEX `codigoVinculo_idx` ON `CadastroCidadao`.`Cidadao` (`codigoVinculo` ASC) VISIBLE;

CREATE INDEX `codigoUF_idx` ON `CadastroCidadao`.`Cidadao` (`codigoUF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Escolaridade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Escolaridade` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Escolaridade` (
  `codigoEscolaridade` INT(1) NOT NULL,
  `descricaoEscolaridade` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigoEscolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Estado_Civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Estado_Civil` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Estado_Civil` (
  `codigoEstadoCivil` INT(1) NOT NULL,
  `descricaoEstadoCivil` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigoEstadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Ocupacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Ocupacao` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Ocupacao` (
  `codigoOcupacao` INT(1) NOT NULL,
  `descricaoOcupacao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigoOcupacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Raca_Cor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Raca_Cor` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Raca_Cor` (
  `codigoRacaCor` INT(1) NOT NULL,
  `descricaoRacaCor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigoRacaCor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`UF` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`UF` (
  `codigoUF` CHAR(2) NOT NULL,
  `descricaoUF` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codigoUF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CadastroCidadao`.`Vinculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CadastroCidadao`.`Vinculo` ;

CREATE TABLE IF NOT EXISTS `CadastroCidadao`.`Vinculo` (
  `codigoVinculo` INT(1) NOT NULL,
  `descricaoVinculo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codigoVinculo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
